@startuml
title: Getting data from the datalayer
footer: Common Gateway | Components
header: Datalyer

skinparam backgroundColor transparent


Request -> Datalayer: Request
Datalayer-> Cache: Update object('s)
Cache--> Datalayer: Object('s)
Datalayer-> Database : Update object('s)
Database --> Datalayer: Object('s)
Datalayer--> Requester: Reponse
@enduml