@startuml
title: Handling PATCH requests
Requester -> Endpoint: Request
Endpoint -> Authorization  : Authorization
Authorization --> Endpoint  : Authorization
Endpoint -> Datalayer : Search object('s)
Datalayer --> Endpoint: Object('s)
Endpoint -> Validation : Validate Request
Validation --> Endpoint: Validation Result
Endpoint -> Datalayer : Update object('s)
Datalayer --> Endpoint: Object('s)
Endpoint --> Requester: Reponse
@enduml