@startuml
title: Handling GET requests
footer: Common Gateway | Endpoints
header: GET Request
autonumber

boundary    Endpoint         as Endpoint
control     Authorization    as Authorization
database    Datalayer        as Datalayer
collections RequestService   as RequestService

Endpoint -> RequestService: Request
RequestService -> Authorization  : Authorization
Authorization --> RequestService  : Authorization
RequestService -> Datalayer : Search object('s)
Datalayer --> RequestService: Object('s)
Endpoint --> Requester: Response
@enduml