@startuml
title: Handling PATCH requests
footer: Common Gateway | Endpoints
header: PATCH Request
autonumber

actor       Requester        as Requester
boundary    Endpoint         as Endpoint
control     Authorization    as Authorization
control     Validation       as Validation
database    Datalayer        as Datalayer

Requester -> Endpoint: Request
Endpoint -> Authorization  : Authorization
Authorization --> Endpoint  : Authorization
Endpoint -> Datalayer : Search object('s)
Datalayer --> Endpoint: Object('s)
Endpoint -> Validation : Validate Request
Validation --> Endpoint: Validation Result
Endpoint -> Datalayer : Update object('s)
Datalayer --> Endpoint: Object('s)
Endpoint --> Requester: Response
@enduml