@startuml
title: Handling DELETE requests
Requester -> Gateway: Request
Gateway -> Authentication  : Authentication
Authentication -> Gateway  : Authentication
Gateway -> Datalayer : Delete object('s)
Datalayer -> Gateway : Object('s)
Gateway --> Requester: Reponse
@enduml