@startuml
title: Handling DELETE requests
footer: Common Gateway | Endpoints
header: DELETE Request
autonumber

boundary    Endpoint         as Endpoint
control     Authorization    as Authorization
database    Datalayer        as Datalayer
collections RequestService   as RequestService

Endpoint -> RequestService: Request
RequestService -> Authorization  : Authorization
Authorization -> RequestService  : Authorization
RequestService -> Datalayer : Delete object('s)
Datalayer -> RequestService : Object('s)
RequestService --> Endpoint: Response
@enduml