@startuml
title: Handling POST requests
footer: Common Gateway | Endpoints
header: POST Request
autonumber

actor       Requester        as Requester
boundary    Endpoint         as Endpoint
control     Authorization    as Authorization
control     Validation       as Validation
database    Datalayer        as Datalayer

Requester -> Endpoint: Request
Endpoint -> Authorization  : Authorization
Authorization -> Endpoint  : Authorization
Endpoint -> Validation : Validate Request
Validation -> Endpoint : Validation Result
Endpoint -> Datalayer : Create object('s)
Datalayer -> Endpoint : Object('s)
Endpoint --> Requester: Response
@enduml