@startuml
title: Handling PUT requests
footer: Common Gateway | Endpoints
header: PUT Request
autonumber

boundary    Endpoint         as Endpoint
collections RequestService   as RequestService
control     Authorization    as Authorization
control     Validation       as Validation
database    Datalayer        as Datalayer

Endpoint -> RequestService: Request
RequestService -> Authorization  : Authorization
Authorization --> RequestService  : Authorization
RequestService -> Validation : Validate Request
Validation --> RequestService : Validation Result
RequestService -> Datalayer: Update object('s)
Datalayer --> RequestService : Object('s)
RequestService --> Endpoint: Response
@enduml