@startuml
title: Handling Proxy
footer: Common Gateway | Endpoints
header: Proxy

autonumber

actor       Requester        as Requester
boundary    Endpoint         as Endpoint
control     Authorization    as Authorization
database    Datalayer        as Datalayer
entity      Source           as Source
collections RequestService   as RequestService

Endpoint -> RequestService: Request
RequestService -> Authorization  : Authorization
Authorization --> RequestService  : Authorization
RequestService -> RequestService : Set authorization for source
RequestService -> Source : Pass Request
Source --> RequestService: Pass Response
RequestService --> Endpoint: Response
@enduml