commongateway_core_metrics:
    resource: "@CoreBundle/src/Controller/MetricsController.php"
    prefix:   /
    type:     annotation

commongateway_core_fileupload:
    resource: "@CoreBundle/src/Controller/FileController.php"
    prefix:   /
    type:     annotation
