# This file is the entry point to configure your own services.
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    CommonGateway\CoreBundle\:
        resource: '../../src/'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/Entity/'
            - '../../src/Resources/'
            - '../../src/CoreBundle.php'
            
    # this config only applies to the services created by this file
    _instanceof:
        # actionHandlers whose classes are instances of ActionHandlerInterface will be tagged automatically and set to public
        CommonGateway\CoreBundle\ActionHandler\ActionHandlerInterface:
            public: true
            tags: ['commongateway.action_handlers']
            
        # installers whose classes are instances of InstallerInterface will be tagged automatically and set to public
        CommonGateway\CoreBundle\Installer\InstallerInterface:
            public: true
            tags: ['commongateway.installer']
           
    monolog.postgresql_connection:
        class: Doctrine\DBAL\Connection
        factory: Doctrine\DBAL\DriverManager::getConnection
        arguments:
            $params:
                url: '%env(CACHE_URL)%'
    monolog.postgresql_handler: 
        class: CommonGateway\CoreBundle\Monolog\PostgresqlHandler
        arguments:
            $connection: '@monolog.postgresql_connection'
            $level: '%log_level%'
