site_name: CoreBundle documentation
site_url: https://test-koor-bundle.readthedocs.io/en/latest/
repo_url: https://github.com/CommonGateway/CoreBundle
docs_dir: docs
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Commands: "./classes/Commands.md"
  # - Schema : "./classes/Schema.md"
  #  - Controller: "./classes/Controller.md"
  # - Data: "./classes/Data.md"
  # - DependencyInjection: "./classes/DependencyInjection.md"
  # - Entity: "./classes/Entity.md"
  # - Installer: "./classes/Installer.md"
  # - Resources: "./classes/Resources.md"
  - Services:
    - AuthenticationService: "./classes/Service/AuthenticationService.md"
    - CacheService: "./classes/Service/CacheService.md"
    - CallService: "./classes/Service/CallService.md"
    - ComposerService: "./classes/Service/ComposerService.md"
    - DownloadService: "./classes/Service/DownloadService.md"
    - EavService: "./classes/Service/EavService.md"
    - FileService: "./classes/Service/FileService.md"
    - FileSystemCreateService: "./classes/Service/FileSystemCreateService.md"
    - FileSystemHandleService: "./classes/Service/FileSystemHandleService.md"
    - GatewayResourceService: "./classes/Service/GatewayResourceService.md"
    - InstallationService: "./classes/Service/InstallationService.md"
    - MappingService: "./classes/Service/MappingService.md"
    - MetricsService: "./classes/Service/MetricsService.md"
    - NotificationService: "./classes/Service/NotificationService.md"
    - OasService: "./classes/Service/OasService.md"
    - RequestService: "./classes/Service/RequestService.md"
    - SchemaService: "./classes/Service/SchemaService.md"
  - Features: 
    - Action_handlers: "./classes/Features/Action_handlers.md"
    - Architecture: "./classes/Features/Architecture.md"
    - Authentication: "./classes/Features/Authentication.md"
    - Authorization: "./classes/Features/Authorization.md"
    - Code_quality: "./classes/Features/Code_quality.md"
    - Commands: "./classes/Features/Commands.md"
    - Cronjobs: "./classes/Features/Cronjobs.md"
    - Datalayer: "./classes/Features/Datalayer.md"
    - Design-decisions: "./classes/Features/Design-decisions.md"
    - Endpoints: "./classes/Features/Endpoints.md"
    - Events: "./classes/Features/Events.md"
    - Features: "./classes/Features/Features.md"
    - Federalization: "./classes/Features/Federalization.md"
    - Logging: "./classes/Features/Logging.md"
    - Mappings: "./classes/Features/Mappings.md"
    - Monitoring: "./classes/Features/Monitoring.md"
    - Notifications: "./classes/Features/Notifications.md"
    - Plugins: "./classes/Features/Plugins.md"
    - Schemas: "./classes/Features/Schemas.md"
    - Security: "./classes/Features/Security.md"
    - Sources: "./classes/Features/Sources.md"
    - Synchronizations: "./classes/Features/Synchronizations.md"
    - Twig: "./classes/Features/Twig.md"
    - Api: "./classes/Features/Api.md"


  
  # Subscriber: "./classes/Subscriber.md"