site_name: CoreBundle documentation
site_url: https://test-koor-bundle.readthedocs.io/en/latest/
repo_url: https://github.com/CommonGateway/CoreBundle
docs_dir: docs
theme:
  name: readthedocs
nav:
  - Home: index.md
  - Commands: "./classes/Commands.md"
  # - Schema : "./classes/Schema.md"
  #  - Controller: "./classes/Controller.md"
  # - Data: "./classes/Data.md"
  # - DependencyInjection: "./classes/DependencyInjection.md"
  # - Entity: "./classes/Entity.md"
  # - Installer: "./classes/Installer.md"
  # - Resources: "./classes/Resources.md"
  - Services:
    - AuthenticationService: "./classes/Service/AuthenticationService.md"
    - CacheService: "./classes/Service/CacheService.md"
    - CallService: "./classes/Service/CallService.md"
    - ComposerService: "./classes/Service/ComposerService.md"
    - DownloadService: "./classes/Service/DownloadService.md"
    - EavService: "./classes/Service/EavService.md"
    - FileService: "./classes/Service/FileService.md"
    - FileSystemCreateService: "./classes/Service/FileSystemCreateService.md"
    - FileSystemHandleService: "./classes/Service/FileSystemHandleService.md"
    - GatewayResourceService: "./classes/Service/GatewayResourceService.md"
    - InstallationService: "./classes/Service/InstallationService.md"
    - MappingService: "./classes/Service/MappingService.md"
    - MetricsService: "./classes/Service/MetricsService.md"
    - NotificationService: "./classes/Service/NotificationService.md"
    - OasService: "./classes/Service/OasService.md"
    - RequestService: "./classes/Service/RequestService.md"
    - SchemaService: "./classes/Service/SchemaService.md"
  - Features: 
    - Action_handlers: "./Features/Action_handlers.md"
    - Architecture: "./Features/Architecture.md"
    - Authentication: "./Features/Authentication.md"
    - Authorization: "./Features/Authorization.md"
    - Code_quality: "./Features/Code_quality.md"
    - Commands: "./Features/Commands.md"
    - Cronjobs: "./Features/Cronjobs.md"
    - Datalayer: "./Features/Datalayer.md"
    - Design-decisions: "./Features/Design-decisions.md"
    - Endpoints: "./Features/Endpoints.md"
    - Events: "./Features/Events.md"
    - Features: "./Features/Features.md"
    - Federalization: "./Features/Federalization.md"
    - Logging: "./Features/Logging.md"
    - Mappings: "./Features/Mappings.md"
    - Monitoring: "./Features/Monitoring.md"
    - Notifications: "./Features/Notifications.md"
    - Plugins: "./Features/Plugins.md"
    - Schemas: "./Features/Schemas.md"
    - Security: "./Features/Security.md"
    - Sources: "./Features/Sources.md"
    - Synchronizations: "./Features/Synchronizations.md"
    - Twig: "./Features/Twig.md"
    - Api: "./Features/Api.md"


  
  # Subscriber: "./classes/Subscriber.md"