#bassed on https://github.com/marketplace/actions/auto-comment
name: Auto Comment
on: [issues, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}
            Thank you for raising an issue. We will investigate the matter and get back to you as soon as possible.
            Please make sure you have given us as much context as possible.
          pullRequestOpenedReactions: 'hooray, +1'
          pullRequestOpenedComment: |
            👋 @{{ author }}
            Thank you for raising your pull request.
            Please make sure you have followed our contributing guidelines. We will review it as soon as possible. In the meanwhile make sure your PR checks the following boxes           
            - [ ] Is based on an issue
            - [ ] Has been locally tested
            - [ ] Has been tested with the admin UI
            - [ ] Has been discussed with the development team in an open channel
