name: Docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          php_extensions: redis exif mongodb zip
          version: 2.x
          command: require clean/phpdoc-md
      - name: Build the docs
        run: vendor/bin/phpdoc-md
      - name: Git commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git add docs/classes
          git commit -m "Update phpdoc" || echo "No changes to commit"
          git pull origin $(git rev-parse --abbrev-ref HEAD) --rebase --autostash
          git push