# Turns al the markdown files into a pdf for future downloads based on https://www.stevefenton.co.uk/blog/2022/04/converting-markdown-files-to-pdf-in-github-actions/
name: convert

on:
  push:

# todo turn the folder into a variable
jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build book
        run: |-
          npm install -g md-to-pdf
          echo; echo "Adding root to PDF"
          for f in *.md; do cat $f; echo; done | md-to-pdf > docs/manual.pdf
          cd docs
          echo; echo "Input Folder docs"
          ls
          echo; echo "Adding docs to PDF"
          for f in *.md; do cat $f; echo; done | md-to-pdf > manual.pdf
          cd features
          echo; echo "Input Folder docs/features"
          ls
          echo; echo "Adding features to PDF"
          for f in *.md; do cat $f; echo; done | md-to-pdf > ../manual.pdf
          cd ../
          echo; echo "Output DOCS Folder Listing"
          ls
          cd ..
      - name: Git commit
        run: |
          git config user.name "GitHub Actions"
          git config user.email ""
          git add docs/manual.pdf
          git commit -m "Update docs from PDF Manual creator" || echo "No changes to commit"
          git pull origin $(git rev-parse --abbrev-ref HEAD) --rebase --autostash
          git push