name: php-unit

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_version: "7.4"
          php_extensions: redis exif
          version: 2.x
          command: require symfony/test-pack
      - name: ls all
        run: ls -la vendor
      - name: Run tests
        run: php vendor/bin/phpunit --coverage-text=tests/results/phpunit.txt
      - name: Output the run Details
        if: (success() || failure())
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: tests/results